/**
 * URLs of the boundary files in `src/lib/geo/` (generated by scripts/prepare-geo-data.ts). Imported
 * via `?url` so Vite emits them as content-hashed assets under `_app/immutable/` — the production
 * server then serves them precompressed with a one-year immutable Cache-Control, and a regenerated
 * file gets a new URL automatically. (Plain `static/` files got neither.)
 */
const urls = import.meta.glob<string>('../geo/*.json', {
	query: '?url',
	import: 'default',
	eager: true
});

function geoUrl(name: string): string {
	const url = urls[`../geo/${name}.json`];
	if (!url) throw new Error(`missing geo file: ${name}.json`);
	return url;
}

export const GEO_URL = {
	regierungsbezirk: geoUrl('regierungsbezirk'),
	kreis: geoUrl('kreis'),
	gemeinde: geoUrl('gemeinde'),
	wahlkreisBundestag: geoUrl('wahlkreis-bundestag'),
	wahlkreisLandtag: geoUrl('wahlkreis-landtag')
};

/** Stuttgart's Wahlbezirk boundaries as of one election date, or null when none exist for it. */
export function stuttgartBezirkeUrl(date: string): string | null {
	return urls[`../geo/stuttgart-bezirke-${date}.json`] ?? null;
}
